Optimized pattern recognition

diff --git a/dcp b/dcp
--- a/dcp
+++ b/dcp
@@ -3,11 +3,11 @@
 function usage 
 {
   echo -e "No ip address\nUsage: $(basename "$0") [-d] [-l] -i ip [-t localdir] [remotedir ... ]"
-  printf "\t-l long format\n\t-d only list directories and files\n" 
+  printf "\t-l long format\n\t-d only list directories and files\n\n\t-v verbose curl\n" 
   exit 1
 }
 
-while getopts ldi:t: opt; do
+while getopts vldi:t: opt; do
     case $opt in
         l) longformatopt=1
             ;;
@@ -18,6 +18,8 @@ while getopts ldi:t: opt; do
         t) targetdir=$OPTARG
            cd "$targetdir" || exit 1
            ;;
+        v) verbose='-v'
+           ;;
     esac
 done
 
@@ -27,7 +29,7 @@ if [[ -z "$targetdir" ]]; then
   configdir=$(ddir -i "$ip"); 
   if [[ ! -z "$configdir" ]]; then
       cd "$configdir"  ||  exit 1; 
-      [[ -z "$listdir" ]] &&  echo "Files downloaded to $(pwd)"
+      
   else
      echo "Download directory not found in configuration for $ip"
      exit 1
@@ -35,8 +37,6 @@ if [[ -z "$targetdir" ]]; then
 fi 
 
 shift "$((OPTIND-1))"
-
-server=$(dserver -i "$ip")
 
 function print_properties
 {
@@ -54,6 +54,7 @@ function set_regex_pattern
   pattern=${basename/\./\\.}  #substitute  . with \.
   pattern=${pattern//\*/.\*}  #            * with .* 
   pattern=${pattern//\?/.}    #            ? with .
+ 
 }
 
 function print_dir
@@ -77,6 +78,8 @@ function print_dir
     else
         attr="-r--r--r--"
         if [[ ${dprop[0]} =~ $pattern ]]; then
+        (( numfiles++ ))
+        [[ ! -z $verbose && -z $listdir ]] && echo "$dir/${dprop[0]} -> $(pwd)/${dprop[0]}"
           pagefiles+="http://$ip/cgi-bin/sddownload.cgi?file=$dir/${dprop[0]} "
           print_properties dprop[3]
         #Format: http://192.168.0.106/cgi-bin/sddownload.cgi?file=/video/20180103/00/p120180103_003150.mp4
@@ -99,21 +102,23 @@ function print_dir_dcs-lig-httpd
     for item in ${list[*]}; do
       IFS=":" read -r -a dprop <<< "$item" 
 
-    dprop[2]=${dprop[2]%\*} #strip off * suffix from file size
+      dprop[2]=${dprop[2]%\*} #strip off * suffix from file size
 
-    if [[ "${dprop[1]}" == "d" ]]; then
-          attr="drwxrwxr--"
-          dprop[2]=0 # is -1
-          timestamp=$(date -d"$dir ${dprop[0]}" +'%b %e %T') # No date available, infer from dir
-          print_properties dprop[2]
-      else
-          attr="-r--r--r--"
-          if [[  ${dprop[0]} =~ $pattern ]]; then
-          #Fromat: http://192.168.0.110/cgi/admin/getSDFile.cgi?file=20180110_063000.mp4&path=DCS-936L/20180110/06/20180110_063000.mp4
-            timestamp=$(date -d"${dprop[0]:0:8} ${dprop[0]:9:2}:${dprop[0]:11:2}:${dprop[0]:13:2}" +'%b %e %T') # no date avail., infer from basename
-            pagefiles+="http://$ip/cgi/admin/getSDFile.cgi?file=${dprop[0]}&path=$product/$dir/${dprop[0]} "
+      if [[ "${dprop[1]}" == "d" ]]; then
+            attr="drwxrwxr--"
+            dprop[2]=0 # is -1
+            timestamp=$(date -d"$dir ${dprop[0]}" +'%b %e %T') # No date available, infer from dir
             print_properties dprop[2]
-          fi
+      else
+            attr="-r--r--r--"
+            if [[  ${dprop[0]} =~ $pattern ]]; then
+            #Fromat: http://192.168.0.110/cgi/admin/getSDFile.cgi?file=20180110_063000.mp4&path=DCS-936L/20180110/06/20180110_063000.mp4
+              timestamp=$(date -d"${dprop[0]:0:8} ${dprop[0]:9:2}:${dprop[0]:11:2}:${dprop[0]:13:2}" +'%b %e %T') # no date avail., infer from basename
+              (( numfiles++ ))
+              [[ ! -z $verbose && -z $listdir ]] && echo "$dir/${dprop[0]} -> $(pwd)/${dprop[0]}"
+              pagefiles+="http://$ip/cgi/admin/getSDFile.cgi?file=${dprop[0]}&path=$product/$dir/${dprop[0]} "
+              print_properties dprop[2]
+            fi
       fi
       
     done
@@ -123,18 +128,19 @@ function parse_page
 {
   totalpages=1
   currentpage=0
-
-  pagefiles=
+  numfiles=0;
 
   until (( currentpage >= totalpages )); do
+
+    pagefiles=
   
     ((currentpage++))
   
     if [[ $(dreq "http://$ip/cgi-bin/sdoperate.cgi?list=&path=$dir&page=$currentpage") == *"500 Internal Error"* ]]; then
       # Trying to access non-existent directory gives "500 Internal Error" response
   
-        echo "Failed to open '$dir': 500 Internal Error"
-          continue
+        echo "Failed to open '$dir'"
+        continue
       fi
     
       # file/dir-names for each page are embedded in variables inside Javascript <script>-tag
@@ -142,16 +148,36 @@ function parse_page
       # Use FD 10 for read for not interfering with read from stdin inside {}
       while read -r -u 10 line ; do
 
-        [[ "$line" =~ ^var\ g_totalpage ]] &&       { IFS='"' read -r f1 totalpages f3 <<< "$line"; continue;  }
-        [[ "$line" =~ ^var\ g_folderslistStr ]] &&  { IFS='"' read -r f1 folderslistStr f3 <<< "$line"; continue; }
-        [[ "$line" =~ ^var\ g_filelistStr ]] &&     { IFS='"' read -r f1 filelistStr f3 <<< "$line"; break; }
+        if [[ "$line" =~ ^var\ g_totalpage|^var\ g_folderslistStr|^var\ g_filelistStr ]]; then
+
+          case ${BASH_REMATCH[0]} in
+            "var g_totalpage") :
+                IFS='"' read -r f1 totalpages f3 <<< "$line"
+                continue
+                ;;
+            "var g_folderslistStr") :
+                IFS='"' read -r f1 folderslistStr f3 <<< "$line"
+                continue
+                ;;
+            "var g_filelistStr") : 
+                IFS='"' read -r f1 filelistStr f3 <<< "$line"
+                break
+                ;;
+          esac
+    
+        fi
 
       done 10< <(dreq "http://$ip/setup_sdlist.htm")
 
       print_dir "$folderslistStr"
       print_dir "$filelistStr"
 
-      dirfiles+=$pagefiles 
+      if [ -z "$basename" ]; then
+        dirfiles+=$pagefiles 
+      else
+        dirfiles=$pagefiles
+      fi;
+
     done
   }
 
@@ -160,29 +186,58 @@ function parse_page
     totalpages=1
     currentpage=0
     sdfpp=100
-
-    pagefiles=
+    numfiles=0;
 
     until (( currentpage >= totalpages )); do
+
+      pagefiles=
     
       ((currentpage++))
     
       while read -r line ; do
 
-      [[ "$line" =~ ^\<product\> ]] && { prefix=${line#<product>}; product=${prefix%</product>}; }
-      [[ "$line" =~ ^\<totalpages\> ]] && { prefix=${line#<totalpages>}; totalpages=${prefix%</totalpages>}; }
-      [[ "$line" =~ ^\<folderstring\> ]] && { prefix=${line#<folderstring>}; folderstring=${prefix%</folderstring>}; }
+        if [[ "$line" =~ ^\<product\>|^\<totalpages\>|^\<folderstring\> ]]; then
+          
+          case ${BASH_REMATCH[0]} in
+            "<product>") :
+              prefix=${line#<product>}
+              product=${prefix%</product>} 
+            ;;
+            "<totalpages>") : 
+              prefix=${line#<totalpages>}
+              totalpages=${prefix%</totalpages>} 
+            ;;
+            "<folderstring>") :  
+              prefix=${line#<folderstring>} 
+              folderstring=${prefix%</folderstring>}
+              ;;
+          esac
 
-    done < <(dreq "http://$ip/eng/admin/adv_sdcard.cgi?folderpath=$dir&command=video&filesperpage=$sdfpp&currentpage=$currentpage")
+        fi
 
-    # Attempt to access non-existent directory gives 400 Bad request response
-    [[ ! -z "$folderstring" ]] && print_dir_dcs-lig-httpd "$folderstring"
+      done < <(dreq "http://$ip/eng/admin/adv_sdcard.cgi?folderpath=$dir&command=video&filesperpage=$sdfpp&currentpage=$currentpage")
 
-    dirfiles+=$pagefiles 
-  done
+      # Attempt to access non-existent directory gives 400 Bad request response
+      [[ ! -z "$folderstring" ]] && print_dir_dcs-lig-httpd "$folderstring"
+
+      if [ -z "$basename" ]; then
+        dirfiles+=$pagefiles 
+      else
+        dirfiles=$pagefiles
+      fi;
+
+   done
+
 }
 
 dir=$1
+
+server=$(dserver -i "$ip")
+
+if [[ -z $server ]] ; then
+  echo "Failed to get server for $ip"
+  exit 1
+fi
 
 case $server in
    
@@ -208,7 +263,7 @@ case $server in
         
         parse_page
 
-        [[ ! -z $dirfiles && ! $listdir ]] && dreq -v --remote-header-name --remote-name-all $dirfiles
+        [[ ! -z $dirfiles && ! $listdir ]] && { echo "$dir -> $(pwd) ($numfiles for download)"; dreq $verbose --remote-header-name --remote-name-all $dirfiles; }
 
         shift;
 
@@ -236,7 +291,7 @@ case $server in
 
         parse_page_dcs-lig-httpd
 
-        [[ ! -z $dirfiles && ! $listdir ]] && dreq -v --remote-header-name --remote-name-all $dirfiles
+        [[ ! -z $dirfiles && ! $listdir ]] && { echo "$dir -> $(pwd) ($numfiles files)"; dreq $verbose --remote-header-name --remote-name-all $dirfiles; }
 
         shift;
 
diff --git a/dpoll b/dpoll
--- a/dpoll
+++ b/dpoll
@@ -17,6 +17,12 @@ done
 shift "$((OPTIND-1))"
 
 server=$(dserver -i "$ip")
+
+if [[ -z $server ]]; then
+   echo "Failed to get server for ip $ip"
+   exit 1;
+fi
+
 read -r Y m d H M < <(date -d'1 hours ago' +'%Y %m %d %H %M')
 
 case $server in
