Added sdir to get directory name for video files for specific camera

diff --git a/getsleep b/getsleep
--- a/getsleep
+++ b/getsleep
@@ -4,41 +4,30 @@
 #set -x 
 #trap read debug
 
-
 verbose="-v"
 
 if [ -z "$1" ]; then
-  echo "Usage: gsl {ipadr}"
+  echo "Usage: gsl ipadr"
   exit 1
 fi
 
 ipadr=$1
-curlopt="-u admin: --anyauth -s --compressed -e http://$ipadr/"
-
-# shellcheck disable=2086
-devstat=$(curl $curlopt  "http://$ipadr/eng/admin/st_device.cgi")
-#Serial (used as directory) should be next level from root directory on camera SD card, otherwise access problems will occur "501 not implemented" response
-# head inserted in pipe chain to avoid write error (broken pipe) to pipe into grep -m 1 
-devstathead=$(tr ' ' '\n' <<< "$devstat" | head -n 15)
-serial=$(grep serial <<< "$devstathead" | cut -d ">" -f 2 | cut -d "<" -f 1)
-camname=$(grep cameraName <<< "$devstathead" | cut -d ">" -f 2 | cut -d "<" -f 1)
-if [ -z "$camname" ]; then
-  camuniq=$serial-$ipadr
-else
-  camuniq=$camname-$serial-$ipadr
-fi
-
+sdir=$(sdir "$ipadr")
+camuniq=$(echo "$sdir" | cut -d ' ' -f 1)
+serial=$(echo "$sdir" | cut -d ' ' -f 2)
+camname=$(echo "$sdir" | cut -d ' ' -f 3)
 guess_viddir=$(ls -d "$HOME"/*/ | grep -m 1 Video)
 viddir=$guess_viddir$camuniq
-cd "$viddir" || { echo "Failed to cd into $viddir"; if [ ! -d "$viddir" ]; then mkdir -v  "$viddir"; cd "$viddir" || { echo "Failed to cd into $viddir, using $PWD"; viddir=$PWD; } fi }
 camlog="$guess_viddir$camuniq/camera.log"
-
+cd "$viddir" || { echo "Failed to cd into $viddir"; if [ ! -d "$viddir" ]; then mkdir -v  "$viddir"; cd "$viddir" || { echo "Failed to cd into $viddir, using $PWD"; viddir=$PWD; } fi }
 
 # Max. command line size bash; getconf ARG_MAX
 #https://stackoverflow.com/questions/19354870/bash-command-line-and-input-limit
 
 echo "Log $serial camera $camname at $ipadr -> $camlog"
 echo "Video directory $serial camera $camname at $ipadr -> $viddir"
+curlopt="-u admin: --anyauth -s --compressed -e http://$ipadr/"
+
 # shellcheck disable=2086
 motionlog=$(curl $curlopt --data 'export=true'  "http://$ipadr/eng/admin/export_log.cgi" | tee "$camlog"  | grep -E "Motion.*SD Card is OK" | cut -d' ' -f4)
 
